// Expanded preset habits — gallery-style with categories and icons
// Sources: Andrew Huberman, James Clear, BJ Fogg + user-requested habits from reference app

export type HabitCategory = 'suggested' | 'life' | 'health' | 'sports' | 'mindset';

export interface PresetHabit {
  name: string;
  description: string;
  icon: string;
  category: HabitCategory;
  cue: string;
  routine: string;
  reward: string;
  time_of_day: 'morning' | 'afternoon' | 'evening' | 'anytime';
  source: string;
}

export const HABIT_CATEGORIES: { key: HabitCategory; label: string }[] = [
  { key: 'suggested', label: 'Suggested' },
  { key: 'life', label: 'Life' },
  { key: 'health', label: 'Health' },
  { key: 'sports', label: 'Sports' },
  { key: 'mindset', label: 'Mindset' },
];

export const PRESET_HABITS: PresetHabit[] = [
  // ─── SUGGESTED (research-backed top picks) ───
  {
    name: 'View sunlight',
    description: 'Set your circadian clock and feel alert',
    icon: '☀️',
    category: 'suggested',
    cue: 'When I wake up',
    routine: 'Go outside for 5-10 minutes',
    reward: 'Feel alert and energized',
    time_of_day: 'morning',
    source: 'Andrew Huberman — circadian biology',
  },
  {
    name: 'Hydrate first',
    description: 'Water before anything else',
    icon: '💧',
    category: 'suggested',
    cue: 'When I get out of bed',
    routine: 'Drink 16-32 oz of water',
    reward: 'Feel clear-headed',
    time_of_day: 'morning',
    source: 'Huberman — neuron function',
  },
  {
    name: 'Move your body',
    description: 'Any movement counts, even 10 minutes',
    icon: '🏃',
    category: 'suggested',
    cue: 'After I have water',
    routine: 'Move for at least 10 minutes',
    reward: 'Elevated mood and energy',
    time_of_day: 'morning',
    source: 'Huberman — linchpin habits',
  },
  {
    name: 'Gratitude list',
    description: 'Three things you are grateful for',
    icon: '🙏',
    category: 'suggested',
    cue: 'After dinner or before bed',
    routine: 'Write or say 3 things I am grateful for',
    reward: 'Better sleep, increased positivity',
    time_of_day: 'evening',
    source: 'Emmons & McCullough (2003)',
  },
  {
    name: 'Read',
    description: 'A chapter a day will light your way',
    icon: '📖',
    category: 'suggested',
    cue: 'After I get into bed',
    routine: 'Read for at least 10 minutes',
    reward: 'Learning something new',
    time_of_day: 'evening',
    source: 'James Clear — compounding gains',
  },
  {
    name: 'Meditate',
    description: 'Quiet your mind and let the soul speak',
    icon: '🧘',
    category: 'suggested',
    cue: 'After lunch',
    routine: '10 minutes of meditation or NSDR',
    reward: 'Feel refreshed and recharged',
    time_of_day: 'afternoon',
    source: 'Huberman — NSDR research',
  },
  {
    name: 'Evening reflection',
    description: 'Process your day through journaling',
    icon: '📝',
    category: 'suggested',
    cue: 'After dinner',
    routine: 'Open the app and reflect',
    reward: 'Closure on the day',
    time_of_day: 'evening',
    source: 'Pennebaker — expressive writing',
  },
  {
    name: 'Send a good morning text',
    description: 'One message can change someone\'s day',
    icon: '💬',
    category: 'suggested',
    cue: 'While having morning coffee',
    routine: 'Text one person I care about',
    reward: 'Feel connected',
    time_of_day: 'morning',
    source: 'Jay Shetty & Huberman — social bonding',
  },

  // ─── LIFE ───
  {
    name: 'Daily Check-in',
    description: 'Try a little harder to be a little better',
    icon: '😊',
    category: 'life',
    cue: 'At the end of the day',
    routine: 'Ask myself: did I show up today?',
    reward: 'Self-awareness',
    time_of_day: 'evening',
    source: 'Self-reflection practice',
  },
  {
    name: 'Learn Musical Instruments',
    description: 'Get some inspiration from your own melodies',
    icon: '🎹',
    category: 'life',
    cue: 'After work or school',
    routine: 'Practice instrument for 15 minutes',
    reward: 'Creative expression',
    time_of_day: 'afternoon',
    source: 'Neuroplasticity research',
  },
  {
    name: 'Listen to Music',
    description: 'Get in the right mood',
    icon: '🎵',
    category: 'life',
    cue: 'During commute or break',
    routine: 'Put on a favorite playlist',
    reward: 'Mood boost',
    time_of_day: 'anytime',
    source: 'Music therapy research',
  },
  {
    name: 'Watch a Movie',
    description: 'Experience life in another way',
    icon: '🎬',
    category: 'life',
    cue: 'Weekend evening',
    routine: 'Watch something meaningful',
    reward: 'New perspective, relaxation',
    time_of_day: 'evening',
    source: 'Creative enrichment',
  },
  {
    name: 'Reduce Screen Time',
    description: 'Disconnect from the phone and reconnect with life',
    icon: '📵',
    category: 'life',
    cue: 'When I feel the urge to scroll',
    routine: 'Put phone in another room for 30 min',
    reward: 'Presence and clarity',
    time_of_day: 'anytime',
    source: 'James Clear — friction for bad habits',
  },
  {
    name: 'Learn New Words',
    description: 'Small number, big result',
    icon: '📚',
    category: 'life',
    cue: 'During morning coffee',
    routine: 'Learn 3 new words',
    reward: 'Expanded vocabulary',
    time_of_day: 'morning',
    source: 'Cognitive enrichment',
  },
  {
    name: 'Learn a New Language',
    description: 'Open up a new window to look at the world',
    icon: '🌍',
    category: 'life',
    cue: 'After lunch',
    routine: '15 minutes of language practice',
    reward: 'New connections and perspectives',
    time_of_day: 'afternoon',
    source: 'Huberman — neuroplasticity',
  },
  {
    name: 'Connect with Nature',
    description: 'Step outside and breathe it in',
    icon: '🌿',
    category: 'life',
    cue: 'During a break',
    routine: 'Spend 10 minutes outdoors',
    reward: 'Calm and grounded',
    time_of_day: 'anytime',
    source: 'Nature exposure research',
  },

  // ─── HEALTH ───
  {
    name: 'Drink Water',
    description: 'Stay moisturized',
    icon: '🥤',
    category: 'health',
    cue: 'Every hour',
    routine: 'Drink a full glass of water',
    reward: 'Sustained energy',
    time_of_day: 'anytime',
    source: 'Huberman — hydration',
  },
  {
    name: 'Eat Breakfast',
    description: 'Life begins after breakfast',
    icon: '🍳',
    category: 'health',
    cue: 'Within an hour of waking',
    routine: 'Prepare a nutritious breakfast',
    reward: 'Steady energy for the morning',
    time_of_day: 'morning',
    source: 'Nutrition science',
  },
  {
    name: 'Eat Dinner',
    description: 'The best memories happen around the table',
    icon: '🍽️',
    category: 'health',
    cue: 'At a consistent evening time',
    routine: 'Sit down for a proper meal',
    reward: 'Nourishment and connection',
    time_of_day: 'evening',
    source: 'Mindful eating research',
  },
  {
    name: 'Eat Fruits',
    description: 'Stay healthier, stay happier',
    icon: '🍌',
    category: 'health',
    cue: 'As a snack',
    routine: 'Choose fruit over processed food',
    reward: 'Vitamins and natural energy',
    time_of_day: 'anytime',
    source: 'Nutrition science',
  },
  {
    name: 'Eat Veggies',
    description: 'Intake fibers to help you digest well',
    icon: '🥕',
    category: 'health',
    cue: 'When serving a meal',
    routine: 'Put vegetables on the plate first',
    reward: 'Better digestion and health',
    time_of_day: 'anytime',
    source: 'James Clear — habit stacking',
  },
  {
    name: 'Quit Snacks',
    description: 'Stop emotional eating',
    icon: '🚫',
    category: 'health',
    cue: 'When craving a snack',
    routine: 'Drink water or go for a walk instead',
    reward: 'Healthier relationship with food',
    time_of_day: 'anytime',
    source: 'Behavioral change research',
  },
  {
    name: 'Quit Sugar',
    description: 'You are sweet enough already',
    icon: '🍬',
    category: 'health',
    cue: 'When offered sweets',
    routine: 'Choose a natural alternative',
    reward: 'Stable energy, clearer skin',
    time_of_day: 'anytime',
    source: 'Nutrition research',
  },
  {
    name: 'Early to Rise',
    description: 'Get up and be amazing',
    icon: '🌅',
    category: 'health',
    cue: 'When alarm goes off',
    routine: 'Get out of bed immediately, no snooze',
    reward: 'More time, sense of control',
    time_of_day: 'morning',
    source: 'Huberman — circadian phase 1',
  },
  {
    name: 'Early to Bed',
    description: 'Rest is the foundation of everything',
    icon: '🌙',
    category: 'health',
    cue: 'At 10 PM',
    routine: 'Screen off, lights dim, into bed',
    reward: 'Deep restorative sleep',
    time_of_day: 'evening',
    source: 'Huberman — sleep optimization',
  },
  {
    name: 'Cold Exposure',
    description: 'Boost your dopamine naturally',
    icon: '🧊',
    category: 'health',
    cue: 'After workout',
    routine: '1-3 minutes of cold water',
    reward: 'Lasting energy and mental clarity',
    time_of_day: 'morning',
    source: 'Huberman — cold exposure',
  },

  // ─── SPORTS ───
  {
    name: 'Stretch',
    description: 'More stretching, less stressing',
    icon: '🤸',
    category: 'sports',
    cue: 'After waking up',
    routine: '5 minutes of full body stretching',
    reward: 'Flexibility and reduced tension',
    time_of_day: 'morning',
    source: 'Physical therapy research',
  },
  {
    name: 'Run',
    description: 'As we run, we become',
    icon: '🏃',
    category: 'sports',
    cue: 'Put on running shoes',
    routine: 'Run for at least 15 minutes',
    reward: 'Runner\'s high, cardiovascular health',
    time_of_day: 'morning',
    source: 'Huberman — Zone II cardio',
  },
  {
    name: 'Yoga',
    description: 'Bring peace to the moment. Namaste!',
    icon: '🧘',
    category: 'sports',
    cue: 'Morning or evening',
    routine: '15-20 minutes of yoga',
    reward: 'Balance, flexibility, inner calm',
    time_of_day: 'morning',
    source: 'Mind-body research',
  },
  {
    name: 'Do Push-Ups',
    description: 'Take your power back',
    icon: '💪',
    category: 'sports',
    cue: 'Before shower',
    routine: 'Do as many push-ups as I can',
    reward: 'Strength and discipline',
    time_of_day: 'morning',
    source: 'BJ Fogg — two-minute rule',
  },
  {
    name: 'Go Cycling',
    description: 'Happiness is riding my bike downhill',
    icon: '🚴',
    category: 'sports',
    cue: 'Weekend or after work',
    routine: 'Cycle for 20+ minutes',
    reward: 'Freedom and cardio health',
    time_of_day: 'afternoon',
    source: 'Cardiovascular research',
  },
  {
    name: 'Swim',
    description: 'Let waves be your company',
    icon: '🏊',
    category: 'sports',
    cue: 'Scheduled swim time',
    routine: 'Swim for 20+ minutes',
    reward: 'Full body workout, calm mind',
    time_of_day: 'anytime',
    source: 'Exercise science',
  },
  {
    name: 'Exercise',
    description: 'Energize your body and sharpen your mind',
    icon: '🏋️',
    category: 'sports',
    cue: 'Scheduled workout time',
    routine: 'Complete a workout session',
    reward: 'Strength, energy, confidence',
    time_of_day: 'morning',
    source: 'Huberman — linchpin habits',
  },
  {
    name: 'Walk',
    description: 'The simplest path to clarity',
    icon: '🚶',
    category: 'sports',
    cue: 'After a meal',
    routine: 'Walk for 15-20 minutes',
    reward: 'Better digestion, clear thinking',
    time_of_day: 'anytime',
    source: 'Walking research',
  },

  // ─── MINDSET ───
  {
    name: 'Take a Deep Breath',
    description: 'Breath, it calms the mind',
    icon: '🌬️',
    category: 'mindset',
    cue: 'When feeling stressed',
    routine: '2-3 physiological sighs',
    reward: 'Immediate calm',
    time_of_day: 'anytime',
    source: 'Huberman — physiological sigh',
  },
  {
    name: 'Keep Calm',
    description: 'Keep calm and carry on',
    icon: '🌈',
    category: 'mindset',
    cue: 'When feeling overwhelmed',
    routine: 'Pause, breathe, choose a response',
    reward: 'Emotional regulation',
    time_of_day: 'anytime',
    source: 'Mindfulness research',
  },
  {
    name: 'Review Today',
    description: 'Did you try your best today?',
    icon: '📋',
    category: 'mindset',
    cue: 'Before bed',
    routine: 'Review what went well and what to improve',
    reward: 'Self-awareness and growth',
    time_of_day: 'evening',
    source: 'Gibbs Reflective Cycle',
  },
  {
    name: 'Praise Others',
    description: 'You are cool with praise',
    icon: '👏',
    category: 'mindset',
    cue: 'When someone does something well',
    routine: 'Give genuine, specific praise',
    reward: 'Stronger relationships',
    time_of_day: 'anytime',
    source: 'James Clear — identity-based habits',
  },
  {
    name: 'Complain Less',
    description: 'Complain never makes anything better',
    icon: '🤐',
    category: 'mindset',
    cue: 'When about to complain',
    routine: 'Reframe into gratitude or a solution',
    reward: 'Positive mindset shift',
    time_of_day: 'anytime',
    source: 'Cognitive reframing research',
  },
  {
    name: 'Self-Reflection',
    description: 'Pain plus reflection equals progress',
    icon: '🪞',
    category: 'mindset',
    cue: 'Evening quiet time',
    routine: 'Journal about one lesson from today',
    reward: 'Deeper self-understanding',
    time_of_day: 'evening',
    source: 'Ray Dalio — Principles',
  },
  {
    name: 'Plan Your Day',
    description: 'Today is going to be a positive day',
    icon: '📅',
    category: 'mindset',
    cue: 'First thing in the morning',
    routine: 'Write top 3 priorities',
    reward: 'Clarity and focus',
    time_of_day: 'morning',
    source: 'Locke & Latham — goal setting',
  },
  {
    name: 'Visualize Tomorrow',
    description: 'See it before you do it',
    icon: '🔮',
    category: 'mindset',
    cue: 'Before falling asleep',
    routine: 'Picture myself going through tomorrow step by step',
    reward: 'Reduced limbic friction',
    time_of_day: 'evening',
    source: 'Huberman — procedural memory',
  },
  {
    name: 'Never Miss Twice',
    description: 'Missing once is human, missing twice is a pattern',
    icon: '🔄',
    category: 'mindset',
    cue: 'When I realize I missed yesterday',
    routine: 'Do the smallest version of the habit today',
    reward: 'Maintained identity',
    time_of_day: 'anytime',
    source: 'James Clear — Atomic Habits',
  },
];
