// Expanded preset habits — gallery-style with categories and icons
// Sources: Andrew Huberman, James Clear, BJ Fogg + user-requested habits from reference app

import { getLocale, type Locale } from './language';

export type HabitCategory = 'suggested' | 'life' | 'health' | 'sports' | 'mindset';

export interface PresetHabit {
  name: string;
  description: string;
  icon: string;
  category: HabitCategory;
  cue: string;
  routine: string;
  reward: string;
  time_of_day: 'morning' | 'afternoon' | 'evening' | 'anytime';
  source: string;
}

export const HABIT_CATEGORIES: { key: HabitCategory; label: string }[] = [
  { key: 'suggested', label: 'Suggested' },
  { key: 'life', label: 'Life' },
  { key: 'health', label: 'Health' },
  { key: 'sports', label: 'Sports' },
  { key: 'mindset', label: 'Mindset' },
];

export const PRESET_HABITS: PresetHabit[] = [
  // ─── SUGGESTED (research-backed top picks) ───
  {
    name: 'View sunlight',
    description: 'Set your circadian clock and feel alert',
    icon: '☀️',
    category: 'suggested',
    cue: 'When I wake up',
    routine: 'Go outside for 5-10 minutes',
    reward: 'Feel alert and energized',
    time_of_day: 'morning',
    source: 'Andrew Huberman — circadian biology',
  },
  {
    name: 'Hydrate first',
    description: 'Water before anything else',
    icon: '💧',
    category: 'suggested',
    cue: 'When I get out of bed',
    routine: 'Drink 16-32 oz of water',
    reward: 'Feel clear-headed',
    time_of_day: 'morning',
    source: 'Huberman — neuron function',
  },
  {
    name: 'Move your body',
    description: 'Any movement counts, even 10 minutes',
    icon: '🏃',
    category: 'suggested',
    cue: 'After I have water',
    routine: 'Move for at least 10 minutes',
    reward: 'Elevated mood and energy',
    time_of_day: 'morning',
    source: 'Huberman — linchpin habits',
  },
  {
    name: 'Gratitude list',
    description: 'Three things you are grateful for',
    icon: '🙏',
    category: 'suggested',
    cue: 'After dinner or before bed',
    routine: 'Write or say 3 things I am grateful for',
    reward: 'Better sleep, increased positivity',
    time_of_day: 'evening',
    source: 'Emmons & McCullough (2003)',
  },
  {
    name: 'Read',
    description: 'A chapter a day will light your way',
    icon: '📖',
    category: 'suggested',
    cue: 'After I get into bed',
    routine: 'Read for at least 10 minutes',
    reward: 'Learning something new',
    time_of_day: 'evening',
    source: 'James Clear — compounding gains',
  },
  {
    name: 'Meditate',
    description: 'Quiet your mind and let the soul speak',
    icon: '🧘',
    category: 'suggested',
    cue: 'After lunch',
    routine: '10 minutes of meditation or NSDR',
    reward: 'Feel refreshed and recharged',
    time_of_day: 'afternoon',
    source: 'Huberman — NSDR research',
  },
  {
    name: 'Evening reflection',
    description: 'Process your day through journaling',
    icon: '📝',
    category: 'suggested',
    cue: 'After dinner',
    routine: 'Open the app and reflect',
    reward: 'Closure on the day',
    time_of_day: 'evening',
    source: 'Pennebaker — expressive writing',
  },
  {
    name: 'Send a good morning text',
    description: 'One message can change someone\'s day',
    icon: '💬',
    category: 'suggested',
    cue: 'While having morning coffee',
    routine: 'Text one person I care about',
    reward: 'Feel connected',
    time_of_day: 'morning',
    source: 'Jay Shetty & Huberman — social bonding',
  },

  // ─── LIFE ───
  {
    name: 'Daily Check-in',
    description: 'Try a little harder to be a little better',
    icon: '😊',
    category: 'life',
    cue: 'At the end of the day',
    routine: 'Ask myself: did I show up today?',
    reward: 'Self-awareness',
    time_of_day: 'evening',
    source: 'Self-reflection practice',
  },
  {
    name: 'Learn Musical Instruments',
    description: 'Get some inspiration from your own melodies',
    icon: '🎹',
    category: 'life',
    cue: 'After work or school',
    routine: 'Practice instrument for 15 minutes',
    reward: 'Creative expression',
    time_of_day: 'afternoon',
    source: 'Neuroplasticity research',
  },
  {
    name: 'Listen to Music',
    description: 'Get in the right mood',
    icon: '🎵',
    category: 'life',
    cue: 'During commute or break',
    routine: 'Put on a favorite playlist',
    reward: 'Mood boost',
    time_of_day: 'anytime',
    source: 'Music therapy research',
  },
  {
    name: 'Watch a Movie',
    description: 'Experience life in another way',
    icon: '🎬',
    category: 'life',
    cue: 'Weekend evening',
    routine: 'Watch something meaningful',
    reward: 'New perspective, relaxation',
    time_of_day: 'evening',
    source: 'Creative enrichment',
  },
  {
    name: 'Reduce Screen Time',
    description: 'Disconnect from the phone and reconnect with life',
    icon: '📵',
    category: 'life',
    cue: 'When I feel the urge to scroll',
    routine: 'Put phone in another room for 30 min',
    reward: 'Presence and clarity',
    time_of_day: 'anytime',
    source: 'James Clear — friction for bad habits',
  },
  {
    name: 'Learn New Words',
    description: 'Small number, big result',
    icon: '📚',
    category: 'life',
    cue: 'During morning coffee',
    routine: 'Learn 3 new words',
    reward: 'Expanded vocabulary',
    time_of_day: 'morning',
    source: 'Cognitive enrichment',
  },
  {
    name: 'Learn a New Language',
    description: 'Open up a new window to look at the world',
    icon: '🌍',
    category: 'life',
    cue: 'After lunch',
    routine: '15 minutes of language practice',
    reward: 'New connections and perspectives',
    time_of_day: 'afternoon',
    source: 'Huberman — neuroplasticity',
  },
  {
    name: 'Connect with Nature',
    description: 'Step outside and breathe it in',
    icon: '🌿',
    category: 'life',
    cue: 'During a break',
    routine: 'Spend 10 minutes outdoors',
    reward: 'Calm and grounded',
    time_of_day: 'anytime',
    source: 'Nature exposure research',
  },

  // ─── HEALTH ───
  {
    name: 'Drink Water',
    description: 'Stay moisturized',
    icon: '🥤',
    category: 'health',
    cue: 'Every hour',
    routine: 'Drink a full glass of water',
    reward: 'Sustained energy',
    time_of_day: 'anytime',
    source: 'Huberman — hydration',
  },
  {
    name: 'Eat Breakfast',
    description: 'Life begins after breakfast',
    icon: '🍳',
    category: 'health',
    cue: 'Within an hour of waking',
    routine: 'Prepare a nutritious breakfast',
    reward: 'Steady energy for the morning',
    time_of_day: 'morning',
    source: 'Nutrition science',
  },
  {
    name: 'Eat Dinner',
    description: 'The best memories happen around the table',
    icon: '🍽️',
    category: 'health',
    cue: 'At a consistent evening time',
    routine: 'Sit down for a proper meal',
    reward: 'Nourishment and connection',
    time_of_day: 'evening',
    source: 'Mindful eating research',
  },
  {
    name: 'Eat Fruits',
    description: 'Stay healthier, stay happier',
    icon: '🍌',
    category: 'health',
    cue: 'As a snack',
    routine: 'Choose fruit over processed food',
    reward: 'Vitamins and natural energy',
    time_of_day: 'anytime',
    source: 'Nutrition science',
  },
  {
    name: 'Eat Veggies',
    description: 'Intake fibers to help you digest well',
    icon: '🥕',
    category: 'health',
    cue: 'When serving a meal',
    routine: 'Put vegetables on the plate first',
    reward: 'Better digestion and health',
    time_of_day: 'anytime',
    source: 'James Clear — habit stacking',
  },
  {
    name: 'Quit Snacks',
    description: 'Stop emotional eating',
    icon: '🚫',
    category: 'health',
    cue: 'When craving a snack',
    routine: 'Drink water or go for a walk instead',
    reward: 'Healthier relationship with food',
    time_of_day: 'anytime',
    source: 'Behavioral change research',
  },
  {
    name: 'Quit Sugar',
    description: 'You are sweet enough already',
    icon: '🍬',
    category: 'health',
    cue: 'When offered sweets',
    routine: 'Choose a natural alternative',
    reward: 'Stable energy, clearer skin',
    time_of_day: 'anytime',
    source: 'Nutrition research',
  },
  {
    name: 'Early to Rise',
    description: 'Get up and be amazing',
    icon: '🌅',
    category: 'health',
    cue: 'When alarm goes off',
    routine: 'Get out of bed immediately, no snooze',
    reward: 'More time, sense of control',
    time_of_day: 'morning',
    source: 'Huberman — circadian phase 1',
  },
  {
    name: 'Early to Bed',
    description: 'Rest is the foundation of everything',
    icon: '🌙',
    category: 'health',
    cue: 'At 10 PM',
    routine: 'Screen off, lights dim, into bed',
    reward: 'Deep restorative sleep',
    time_of_day: 'evening',
    source: 'Huberman — sleep optimization',
  },
  {
    name: 'Cold Exposure',
    description: 'Boost your dopamine naturally',
    icon: '🧊',
    category: 'health',
    cue: 'After workout',
    routine: '1-3 minutes of cold water',
    reward: 'Lasting energy and mental clarity',
    time_of_day: 'morning',
    source: 'Huberman — cold exposure',
  },

  // ─── SPORTS ───
  {
    name: 'Stretch',
    description: 'More stretching, less stressing',
    icon: '🤸',
    category: 'sports',
    cue: 'After waking up',
    routine: '5 minutes of full body stretching',
    reward: 'Flexibility and reduced tension',
    time_of_day: 'morning',
    source: 'Physical therapy research',
  },
  {
    name: 'Run',
    description: 'As we run, we become',
    icon: '🏃',
    category: 'sports',
    cue: 'Put on running shoes',
    routine: 'Run for at least 15 minutes',
    reward: 'Runner\'s high, cardiovascular health',
    time_of_day: 'morning',
    source: 'Huberman — Zone II cardio',
  },
  {
    name: 'Yoga',
    description: 'Bring peace to the moment. Namaste!',
    icon: '🧘',
    category: 'sports',
    cue: 'Morning or evening',
    routine: '15-20 minutes of yoga',
    reward: 'Balance, flexibility, inner calm',
    time_of_day: 'morning',
    source: 'Mind-body research',
  },
  {
    name: 'Do Push-Ups',
    description: 'Take your power back',
    icon: '💪',
    category: 'sports',
    cue: 'Before shower',
    routine: 'Do as many push-ups as I can',
    reward: 'Strength and discipline',
    time_of_day: 'morning',
    source: 'BJ Fogg — two-minute rule',
  },
  {
    name: 'Go Cycling',
    description: 'Happiness is riding my bike downhill',
    icon: '🚴',
    category: 'sports',
    cue: 'Weekend or after work',
    routine: 'Cycle for 20+ minutes',
    reward: 'Freedom and cardio health',
    time_of_day: 'afternoon',
    source: 'Cardiovascular research',
  },
  {
    name: 'Swim',
    description: 'Let waves be your company',
    icon: '🏊',
    category: 'sports',
    cue: 'Scheduled swim time',
    routine: 'Swim for 20+ minutes',
    reward: 'Full body workout, calm mind',
    time_of_day: 'anytime',
    source: 'Exercise science',
  },
  {
    name: 'Exercise',
    description: 'Energize your body and sharpen your mind',
    icon: '🏋️',
    category: 'sports',
    cue: 'Scheduled workout time',
    routine: 'Complete a workout session',
    reward: 'Strength, energy, confidence',
    time_of_day: 'morning',
    source: 'Huberman — linchpin habits',
  },
  {
    name: 'Walk',
    description: 'The simplest path to clarity',
    icon: '🚶',
    category: 'sports',
    cue: 'After a meal',
    routine: 'Walk for 15-20 minutes',
    reward: 'Better digestion, clear thinking',
    time_of_day: 'anytime',
    source: 'Walking research',
  },

  // ─── MINDSET ───
  {
    name: 'Take a Deep Breath',
    description: 'Breath, it calms the mind',
    icon: '🌬️',
    category: 'mindset',
    cue: 'When feeling stressed',
    routine: '2-3 physiological sighs',
    reward: 'Immediate calm',
    time_of_day: 'anytime',
    source: 'Huberman — physiological sigh',
  },
  {
    name: 'Keep Calm',
    description: 'Keep calm and carry on',
    icon: '🌈',
    category: 'mindset',
    cue: 'When feeling overwhelmed',
    routine: 'Pause, breathe, choose a response',
    reward: 'Emotional regulation',
    time_of_day: 'anytime',
    source: 'Mindfulness research',
  },
  {
    name: 'Review Today',
    description: 'Did you try your best today?',
    icon: '📋',
    category: 'mindset',
    cue: 'Before bed',
    routine: 'Review what went well and what to improve',
    reward: 'Self-awareness and growth',
    time_of_day: 'evening',
    source: 'Gibbs Reflective Cycle',
  },
  {
    name: 'Praise Others',
    description: 'You are cool with praise',
    icon: '👏',
    category: 'mindset',
    cue: 'When someone does something well',
    routine: 'Give genuine, specific praise',
    reward: 'Stronger relationships',
    time_of_day: 'anytime',
    source: 'James Clear — identity-based habits',
  },
  {
    name: 'Complain Less',
    description: 'Complain never makes anything better',
    icon: '🤐',
    category: 'mindset',
    cue: 'When about to complain',
    routine: 'Reframe into gratitude or a solution',
    reward: 'Positive mindset shift',
    time_of_day: 'anytime',
    source: 'Cognitive reframing research',
  },
  {
    name: 'Self-Reflection',
    description: 'Pain plus reflection equals progress',
    icon: '🪞',
    category: 'mindset',
    cue: 'Evening quiet time',
    routine: 'Journal about one lesson from today',
    reward: 'Deeper self-understanding',
    time_of_day: 'evening',
    source: 'Ray Dalio — Principles',
  },
  {
    name: 'Plan Your Day',
    description: 'Today is going to be a positive day',
    icon: '📅',
    category: 'mindset',
    cue: 'First thing in the morning',
    routine: 'Write top 3 priorities',
    reward: 'Clarity and focus',
    time_of_day: 'morning',
    source: 'Locke & Latham — goal setting',
  },
  {
    name: 'Visualize Tomorrow',
    description: 'See it before you do it',
    icon: '🔮',
    category: 'mindset',
    cue: 'Before falling asleep',
    routine: 'Picture myself going through tomorrow step by step',
    reward: 'Reduced limbic friction',
    time_of_day: 'evening',
    source: 'Huberman — procedural memory',
  },
  {
    name: 'Never Miss Twice',
    description: 'Missing once is human, missing twice is a pattern',
    icon: '🔄',
    category: 'mindset',
    cue: 'When I realize I missed yesterday',
    routine: 'Do the smallest version of the habit today',
    reward: 'Maintained identity',
    time_of_day: 'anytime',
    source: 'James Clear — Atomic Habits',
  },
];

const HABIT_CATEGORIES_ES: { key: HabitCategory; label: string }[] = [
  { key: 'suggested', label: 'Sugeridos' },
  { key: 'life', label: 'Vida' },
  { key: 'health', label: 'Salud' },
  { key: 'sports', label: 'Deportes' },
  { key: 'mindset', label: 'Mentalidad' },
];

const PRESET_HABITS_ES: PresetHabit[] = [
  // ─── SUGERIDOS ───
  {
    name: 'Ver la luz del sol',
    description: 'Ajusta tu reloj interno y siéntete alerta',
    icon: '☀️',
    category: 'suggested',
    cue: 'Al despertar',
    routine: 'Salir afuera 5-10 minutos',
    reward: 'Sentirme alerta y con energía',
    time_of_day: 'morning',
    source: 'Andrew Huberman — circadian biology',
  },
  {
    name: 'Hidratarme primero',
    description: 'Agua antes que nada',
    icon: '💧',
    category: 'suggested',
    cue: 'Al levantarme',
    routine: 'Tomar 500ml-1L de agua',
    reward: 'Sentirme con claridad mental',
    time_of_day: 'morning',
    source: 'Huberman — neuron function',
  },
  {
    name: 'Mover el cuerpo',
    description: 'Cualquier movimiento cuenta, hasta 10 minutos',
    icon: '🏃',
    category: 'suggested',
    cue: 'Después de tomar agua',
    routine: 'Moverme al menos 10 minutos',
    reward: 'Mejor ánimo y energía',
    time_of_day: 'morning',
    source: 'Huberman — linchpin habits',
  },
  {
    name: 'Lista de gratitud',
    description: 'Tres cosas por las que estoy agradecido',
    icon: '🙏',
    category: 'suggested',
    cue: 'Después de cenar o antes de dormir',
    routine: 'Escribir o decir 3 cosas por las que estoy agradecido',
    reward: 'Mejor sueño, más positividad',
    time_of_day: 'evening',
    source: 'Emmons & McCullough (2003)',
  },
  {
    name: 'Leer',
    description: 'Un capítulo al día ilumina el camino',
    icon: '📖',
    category: 'suggested',
    cue: 'Al meterme a la cama',
    routine: 'Leer al menos 10 minutos',
    reward: 'Aprender algo nuevo',
    time_of_day: 'evening',
    source: 'James Clear — compounding gains',
  },
  {
    name: 'Meditar',
    description: 'Aquieta la mente y deja que el alma hable',
    icon: '🧘',
    category: 'suggested',
    cue: 'Después de comer',
    routine: '10 minutos de meditación o NSDR',
    reward: 'Sentirme renovado y recargado',
    time_of_day: 'afternoon',
    source: 'Huberman — NSDR research',
  },
  {
    name: 'Reflexión nocturna',
    description: 'Procesa tu día a través del diario',
    icon: '📝',
    category: 'suggested',
    cue: 'Después de cenar',
    routine: 'Abrir la app y reflexionar',
    reward: 'Cerrar el día con claridad',
    time_of_day: 'evening',
    source: 'Pennebaker — expressive writing',
  },
  {
    name: 'Enviar un mensaje de buenos días',
    description: 'Un mensaje puede cambiar el día de alguien',
    icon: '💬',
    category: 'suggested',
    cue: 'Mientras tomo café por la mañana',
    routine: 'Mandar un mensaje a alguien que me importa',
    reward: 'Sentirme conectado',
    time_of_day: 'morning',
    source: 'Jay Shetty & Huberman — social bonding',
  },

  // ─── VIDA ───
  {
    name: 'Chequeo diario',
    description: 'Intenta un poquito más ser un poquito mejor',
    icon: '😊',
    category: 'life',
    cue: 'Al final del día',
    routine: 'Preguntarme: ¿di lo mejor de mí hoy?',
    reward: 'Autoconocimiento',
    time_of_day: 'evening',
    source: 'Self-reflection practice',
  },
  {
    name: 'Aprender un instrumento',
    description: 'Inspírate con tus propias melodías',
    icon: '🎹',
    category: 'life',
    cue: 'Después del trabajo o la escuela',
    routine: 'Practicar instrumento 15 minutos',
    reward: 'Expresión creativa',
    time_of_day: 'afternoon',
    source: 'Neuroplasticity research',
  },
  {
    name: 'Escuchar música',
    description: 'Ponte en el mood correcto',
    icon: '🎵',
    category: 'life',
    cue: 'En el camino o en un descanso',
    routine: 'Poner una playlist favorita',
    reward: 'Mejorar el ánimo',
    time_of_day: 'anytime',
    source: 'Music therapy research',
  },
  {
    name: 'Ver una película',
    description: 'Experimenta la vida de otra forma',
    icon: '🎬',
    category: 'life',
    cue: 'Noche de fin de semana',
    routine: 'Ver algo significativo',
    reward: 'Nueva perspectiva, relajación',
    time_of_day: 'evening',
    source: 'Creative enrichment',
  },
  {
    name: 'Reducir tiempo de pantalla',
    description: 'Desconéctate del celular y reconéctate con la vida',
    icon: '📵',
    category: 'life',
    cue: 'Cuando sienta ganas de scrollear',
    routine: 'Dejar el celular en otro cuarto 30 min',
    reward: 'Presencia y claridad',
    time_of_day: 'anytime',
    source: 'James Clear — friction for bad habits',
  },
  {
    name: 'Aprender palabras nuevas',
    description: 'Poco a poco, gran resultado',
    icon: '📚',
    category: 'life',
    cue: 'Durante el café de la mañana',
    routine: 'Aprender 3 palabras nuevas',
    reward: 'Vocabulario más amplio',
    time_of_day: 'morning',
    source: 'Cognitive enrichment',
  },
  {
    name: 'Aprender un idioma nuevo',
    description: 'Abre una nueva ventana para ver el mundo',
    icon: '🌍',
    category: 'life',
    cue: 'Después de comer',
    routine: '15 minutos de práctica de idiomas',
    reward: 'Nuevas conexiones y perspectivas',
    time_of_day: 'afternoon',
    source: 'Huberman — neuroplasticity',
  },
  {
    name: 'Conectar con la naturaleza',
    description: 'Sal y respira profundo',
    icon: '🌿',
    category: 'life',
    cue: 'En un descanso',
    routine: 'Pasar 10 minutos al aire libre',
    reward: 'Calma y conexión con la tierra',
    time_of_day: 'anytime',
    source: 'Nature exposure research',
  },

  // ─── SALUD ───
  {
    name: 'Tomar agua',
    description: 'Mantente hidratado',
    icon: '🥤',
    category: 'health',
    cue: 'Cada hora',
    routine: 'Tomar un vaso lleno de agua',
    reward: 'Energía sostenida',
    time_of_day: 'anytime',
    source: 'Huberman — hydration',
  },
  {
    name: 'Desayunar',
    description: 'La vida empieza después del desayuno',
    icon: '🍳',
    category: 'health',
    cue: 'Dentro de la primera hora al despertar',
    routine: 'Preparar un desayuno nutritivo',
    reward: 'Energía estable por la mañana',
    time_of_day: 'morning',
    source: 'Nutrition science',
  },
  {
    name: 'Cenar',
    description: 'Los mejores recuerdos pasan alrededor de la mesa',
    icon: '🍽️',
    category: 'health',
    cue: 'A una hora fija por la noche',
    routine: 'Sentarme a una comida como es debido',
    reward: 'Nutrición y conexión',
    time_of_day: 'evening',
    source: 'Mindful eating research',
  },
  {
    name: 'Comer frutas',
    description: 'Más sano, más feliz',
    icon: '🍌',
    category: 'health',
    cue: 'Como colación',
    routine: 'Elegir fruta en vez de comida procesada',
    reward: 'Vitaminas y energía natural',
    time_of_day: 'anytime',
    source: 'Nutrition science',
  },
  {
    name: 'Comer verduras',
    description: 'Fibra para una buena digestión',
    icon: '🥕',
    category: 'health',
    cue: 'Al servir la comida',
    routine: 'Poner las verduras en el plato primero',
    reward: 'Mejor digestión y salud',
    time_of_day: 'anytime',
    source: 'James Clear — habit stacking',
  },
  {
    name: 'Dejar los snacks',
    description: 'Dejar de comer por emociones',
    icon: '🚫',
    category: 'health',
    cue: 'Cuando tenga antojo',
    routine: 'Tomar agua o salir a caminar en su lugar',
    reward: 'Mejor relación con la comida',
    time_of_day: 'anytime',
    source: 'Behavioral change research',
  },
  {
    name: 'Reducir el azúcar',
    description: 'Ya eres suficientemente dulce',
    icon: '🍬',
    category: 'health',
    cue: 'Cuando me ofrezcan dulces',
    routine: 'Elegir una alternativa natural',
    reward: 'Energía estable, piel más clara',
    time_of_day: 'anytime',
    source: 'Nutrition research',
  },
  {
    name: 'Madrugar',
    description: 'Levántate y sé increíble',
    icon: '🌅',
    category: 'health',
    cue: 'Cuando suene la alarma',
    routine: 'Levantarme de inmediato, sin snooze',
    reward: 'Más tiempo, sensación de control',
    time_of_day: 'morning',
    source: 'Huberman — circadian phase 1',
  },
  {
    name: 'Dormir temprano',
    description: 'El descanso es la base de todo',
    icon: '🌙',
    category: 'health',
    cue: 'A las 10 PM',
    routine: 'Pantalla apagada, luces bajas, a la cama',
    reward: 'Sueño profundo y reparador',
    time_of_day: 'evening',
    source: 'Huberman — sleep optimization',
  },
  {
    name: 'Exposición al frío',
    description: 'Sube tu dopamina de forma natural',
    icon: '🧊',
    category: 'health',
    cue: 'Después de hacer ejercicio',
    routine: '1-3 minutos de agua fría',
    reward: 'Energía duradera y claridad mental',
    time_of_day: 'morning',
    source: 'Huberman — cold exposure',
  },

  // ─── DEPORTES ───
  {
    name: 'Estirar',
    description: 'Más estiramiento, menos estrés',
    icon: '🤸',
    category: 'sports',
    cue: 'Al despertar',
    routine: '5 minutos de estiramiento de cuerpo completo',
    reward: 'Flexibilidad y menos tensión',
    time_of_day: 'morning',
    source: 'Physical therapy research',
  },
  {
    name: 'Correr',
    description: 'Mientras corremos, nos transformamos',
    icon: '🏃',
    category: 'sports',
    cue: 'Ponerme los tenis para correr',
    routine: 'Correr al menos 15 minutos',
    reward: 'Euforia del corredor, salud cardiovascular',
    time_of_day: 'morning',
    source: 'Huberman — Zone II cardio',
  },
  {
    name: 'Yoga',
    description: 'Trae paz al momento. ¡Namasté!',
    icon: '🧘',
    category: 'sports',
    cue: 'Mañana o noche',
    routine: '15-20 minutos de yoga',
    reward: 'Balance, flexibilidad, calma interior',
    time_of_day: 'morning',
    source: 'Mind-body research',
  },
  {
    name: 'Hacer lagartijas',
    description: 'Recupera tu fuerza',
    icon: '💪',
    category: 'sports',
    cue: 'Antes de bañarme',
    routine: 'Hacer todas las lagartijas que pueda',
    reward: 'Fuerza y disciplina',
    time_of_day: 'morning',
    source: 'BJ Fogg — two-minute rule',
  },
  {
    name: 'Andar en bici',
    description: 'La felicidad es ir en bici cuesta abajo',
    icon: '🚴',
    category: 'sports',
    cue: 'Fin de semana o después del trabajo',
    routine: 'Pedalear 20+ minutos',
    reward: 'Libertad y salud cardiovascular',
    time_of_day: 'afternoon',
    source: 'Cardiovascular research',
  },
  {
    name: 'Nadar',
    description: 'Que las olas te acompañen',
    icon: '🏊',
    category: 'sports',
    cue: 'Hora programada de nado',
    routine: 'Nadar 20+ minutos',
    reward: 'Ejercicio de cuerpo completo, mente tranquila',
    time_of_day: 'anytime',
    source: 'Exercise science',
  },
  {
    name: 'Hacer ejercicio',
    description: 'Energiza tu cuerpo y agudiza tu mente',
    icon: '🏋️',
    category: 'sports',
    cue: 'Hora programada de entrenamiento',
    routine: 'Completar una sesión de ejercicio',
    reward: 'Fuerza, energía, confianza',
    time_of_day: 'morning',
    source: 'Huberman — linchpin habits',
  },
  {
    name: 'Caminar',
    description: 'El camino más simple hacia la claridad',
    icon: '🚶',
    category: 'sports',
    cue: 'Después de comer',
    routine: 'Caminar 15-20 minutos',
    reward: 'Mejor digestión, pensar con claridad',
    time_of_day: 'anytime',
    source: 'Walking research',
  },

  // ─── MENTALIDAD ───
  {
    name: 'Respirar profundo',
    description: 'Respira, calma la mente',
    icon: '🌬️',
    category: 'mindset',
    cue: 'Cuando me sienta estresado',
    routine: '2-3 suspiros fisiológicos',
    reward: 'Calma inmediata',
    time_of_day: 'anytime',
    source: 'Huberman — physiological sigh',
  },
  {
    name: 'Mantener la calma',
    description: 'Mantén la calma y sigue adelante',
    icon: '🌈',
    category: 'mindset',
    cue: 'Cuando me sienta abrumado',
    routine: 'Hacer una pausa, respirar, elegir una respuesta',
    reward: 'Regulación emocional',
    time_of_day: 'anytime',
    source: 'Mindfulness research',
  },
  {
    name: 'Revisar el día',
    description: '¿Diste lo mejor de ti hoy?',
    icon: '📋',
    category: 'mindset',
    cue: 'Antes de dormir',
    routine: 'Revisar qué salió bien y qué mejorar',
    reward: 'Autoconocimiento y crecimiento',
    time_of_day: 'evening',
    source: 'Gibbs Reflective Cycle',
  },
  {
    name: 'Reconocer a otros',
    description: 'Te ves bien cuando reconoces',
    icon: '👏',
    category: 'mindset',
    cue: 'Cuando alguien haga algo bien',
    routine: 'Dar un reconocimiento genuino y específico',
    reward: 'Relaciones más fuertes',
    time_of_day: 'anytime',
    source: 'James Clear — identity-based habits',
  },
  {
    name: 'Quejarme menos',
    description: 'Quejarse nunca mejora nada',
    icon: '🤐',
    category: 'mindset',
    cue: 'Cuando esté a punto de quejarme',
    routine: 'Convertirlo en gratitud o una solución',
    reward: 'Cambio positivo de mentalidad',
    time_of_day: 'anytime',
    source: 'Cognitive reframing research',
  },
  {
    name: 'Autorreflexión',
    description: 'Dolor más reflexión es igual a progreso',
    icon: '🪞',
    category: 'mindset',
    cue: 'En un momento tranquilo de la noche',
    routine: 'Escribir sobre una lección de hoy',
    reward: 'Autoconocimiento más profundo',
    time_of_day: 'evening',
    source: 'Ray Dalio — Principles',
  },
  {
    name: 'Planear tu día',
    description: 'Hoy va a ser un día positivo',
    icon: '📅',
    category: 'mindset',
    cue: 'Lo primero en la mañana',
    routine: 'Escribir las 3 prioridades principales',
    reward: 'Claridad y enfoque',
    time_of_day: 'morning',
    source: 'Locke & Latham — goal setting',
  },
  {
    name: 'Visualizar el mañana',
    description: 'Vélo antes de hacerlo',
    icon: '🔮',
    category: 'mindset',
    cue: 'Antes de dormirme',
    routine: 'Imaginarme pasando por el día de mañana paso a paso',
    reward: 'Menos fricción al empezar',
    time_of_day: 'evening',
    source: 'Huberman — procedural memory',
  },
  {
    name: 'Nunca fallar dos veces',
    description: 'Fallar una vez es humano, fallar dos es un patrón',
    icon: '🔄',
    category: 'mindset',
    cue: 'Cuando me dé cuenta de que fallé ayer',
    routine: 'Hacer la versión más pequeña del hábito hoy',
    reward: 'Mantener mi identidad',
    time_of_day: 'anytime',
    source: 'James Clear — Atomic Habits',
  },
];

export function getLocalizedHabitCategories() {
  return getLocale() === 'es' ? HABIT_CATEGORIES_ES : HABIT_CATEGORIES;
}

export function getLocalizedHabits() {
  return getLocale() === 'es' ? PRESET_HABITS_ES : PRESET_HABITS;
}
